repositoryUrl: https://github.com/dynamsoft-docs/core-docs-js/blob/main
repository: dynamsoft-docs/core-docs-js
docFullPath: https://www.dynamsoft.com/capture-vision/docs/web/
firstLevelUrl: /capture-vision/docs/web/

js: /capture-vision/docs/web/programming/javascript/
js_api: /capture-vision/docs/web/programming/javascript/api-reference/

assets: /capture-vision/docs/web/assets/
edit_icon: /capture-vision/docs/web/assets/img-icon/edit-icon.png
smile_icon: /capture-vision/docs/web/assets/img-icon/icon-smile.png
sad_icon: /capture-vision/docs/web/assets/img-icon/icon-sad.png
dbr_icon: /capture-vision/docs/web/assets/img-icon/icon-dbr.svg
dwt_icon: /capture-vision/docs/web/assets/img-icon/icon-dwt.svg
dnt_icon: /capture-vision/docs/web/assets/img-icon/icon-dnt.svg

useVersionTree: true

baseurl: "/capture-vision/docs/web"
plugins:
  - jemoji
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag

url: "https://www.dynamsoft.com" # sitemap root

